sudo: false
language: python
python:
  - "3.6"
script:
- ls
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  on:
    tags: true
  user: ceball
  password:
    secure: qxvOx0FUW6x4rJ3lEyJdrRLg1dRVUOc1pdh5lWTRhQ25VHG3v4GYporg5J489ni4mdxCVd56sPVTmOKgDk+rtMqFVLH87xMoQvEw0Ep691zEZVJJ4aTgcfCwDh+OajNGkLFLK7OSoM0z7S6S7Wuf83DO4dWJZZ70ey3/KvxHE+xLgI5fO3+bu3zyseLyDo/og/eFRV+w4jG6K1zONcG2RihX9kn00jajshhDkPWtG0FBzKWWRqSqEGTXvibqAcSbL50meBcPc8YHdCVkSsg412GpIOcPQM8Yslz06hj0EuV605fjPDc/sGmGn7ocxEdB9ElMoCB0+XEtPUosP5Taink6StRjvotGwJmjF20YHP3lnLErAzsenjY7VTXmRzwzCXL/L0RaOSE9a6BP/Osq5lOQCFIO4/O3+gE5vyN6Ve6Sh/66Z8UgRMw3whXN8hXF0LqdDmD5p1HdMWZpXrmhz/ju+veR0LGBd2/FKcMxGWxdK+2133MvWLNbrazPs9ytZewJ2fpGzobEZ+wXtVCfMjwRdsuXXkeCbSo2Q7aUZRzSNzQ8qtKhabBXtJEZ2WEeE1W2BcTsp9gKAon1QROJQP31RiAI1Sm/xo9dChKHhyv2XBueujbZLNrxfNm3UgVJXaLrkKe58q8QO2GHnDiT3VXz1fp7tOyycDkvGKCnRVw=  

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./_build/html
  on:
    branch: master


# some conda pain to deal with later
#language: generic
#
#os:
#  - linux
#
#sudo: false
#
#stages:
##  - test
#  - name: deploy
#    if: branch = master AND type != pull_request  
#
#jobs:
#  include:
#    - stage: deploy
#      install:
#      - source ./etc/travis-miniconda.sh
#      # for building and uploading packages
#      - conda install conda-build=3.0.25
#      - conda install anaconda-client
#      script:
#      - conda build conda.recipe
#      - anaconda -t $CONDA_UPLOAD_TOKEN upload --force -u cball $HOME/miniconda/conda-bld/noarch/nbsite*.tar.bz2
#