sudo: false
language: python

stages:
  - test
#  - name: pypi_package
#    if: (branch = master AND type != pull_request) OR (tag =~ ^v)
#  - name: conda_dev_package
#    if: (branch = master AND type != pull_request)
#  - name: conda_package
#    if: tag =~ ^v
#  - name: doc
#    if: (branch = master AND type != pull_request) OR (tag =~ ^v)

jobs:
  include:

    - &default
      stage: test
      python: 3.6
      env: TOX_ENV=py36
      install:
        - pip install tox
      script:
        - tox -e $TOX_ENV

#    - stage: doc
#      python: 3.6
#      install:
#        - pip install -e .
#        - pip install sphinx_ioam_theme
#      script:
#        - cd doc
#        - nbsite_nbpagebuild.py ioam nbsite . .
#        - sphinx-build -b html . ./_build/html
#        - nbsite_fix_links.py _build/html
#        - touch ./_build/html/.nojekyll
#        - nbsite_cleandisthtml.py ./_build/html take_a_chance
#        - cd ..
#
#      deploy:
#        - provider: pages
#          skip_cleanup: true
#          github_token: $GITHUB_TOKEN
#          local_dir: ./doc/_build/html
#          on:
#            tags: true
#
#    - <<: *default
#      stage: pypi_package
#      install: true
#      script: true
#        - provider: pypi
#          distributions: "sdist bdist_wheel"
#          user: ceball
#          password:
#            secure: qxvOx0FUW6x4rJ3lEyJdrRLg1dRVUOc1pdh5lWTRhQ25VHG3v4GYporg5J489ni4mdxCVd56sPVTmOKgDk+rtMqFVLH87xMoQvEw0Ep691zEZVJJ4aTgcfCwDh+OajNGkLFLK7OSoM0z7S6S7Wuf83DO4dWJZZ70ey3/KvxHE+xLgI5fO3+bu3zyseLyDo/og/eFRV+w4jG6K1zONcG2RihX9kn00jajshhDkPWtG0FBzKWWRqSqEGTXvibqAcSbL50meBcPc8YHdCVkSsg412GpIOcPQM8Yslz06hj0EuV605fjPDc/sGmGn7ocxEdB9ElMoCB0+XEtPUosP5Taink6StRjvotGwJmjF20YHP3lnLErAzsenjY7VTXmRzwzCXL/L0RaOSE9a6BP/Osq5lOQCFIO4/O3+gE5vyN6Ve6Sh/66Z8UgRMw3whXN8hXF0LqdDmD5p1HdMWZpXrmhz/ju+veR0LGBd2/FKcMxGWxdK+2133MvWLNbrazPs9ytZewJ2fpGzobEZ+wXtVCfMjwRdsuXXkeCbSo2Q7aUZRzSNzQ8qtKhabBXtJEZ2WEeE1W2BcTsp9gKAon1QROJQP31RiAI1Sm/xo9dChKHhyv2XBueujbZLNrxfNm3UgVJXaLrkKe58q8QO2GHnDiT3VXz1fp7tOyycDkvGKCnRVw=  
#
#    - &conda_default
#      stage: conda_dev_package
#      python: 3.6
#      before_install:
#        - pip install pyct
#        - doit install_miniconda
#        - export PATH="$HOME/miniconda/bin:$PATH"
#        - conda install -y -c pyviz/label/dev -c conda-forge pyct
#        - rm -f .doit.db
#        - doit ci_configure_conda
#      install:
#        - doit build_conda_package --channel conda-forge
#        - conda install --use-local -c conda-forge nbsite
#      script:
#        - cd doc
#        - nbsite_nbpagebuild.py ioam nbsite . .
#        - sphinx-build -b html . ./_build/html
#        - nbsite_fix_links.py _build/html
#        - touch ./_build/html/.nojekyll
#        - nbsite_cleandisthtml.py ./_build/html take_a_chance
#        - cd ..
#      after_success:
#        - doit upload_conda_package --token=$CONDA_UPLOAD_TOKEN
#
#    - <<: *conda_default
#      stage: conda_package
#      after_success:
#        - doit upload_conda_package --token=$CONDA_UPLOAD_TOKEN --label=main --label=dev
