package:
  name: nbsite
  version: {{ load_setup_py_data().get('version') }}

source:
  path: ..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    - python >=3.6
    - jupyter_client
    - ipykernel
    - nbformat
    - nbconvert
    - notebook
    - graphviz
    - sphinx
    - beautifulsoup4
    - graphviz
    - selenium
    - phantomjs

test:
  imports:
    - nbsite
  commands:
    - nbsite_from_tmplate.py /tmp/doc

about:
  home: https://github.com/ioam/nbsite
  summary: Build a tested, sphinx-based website from notebooks.
  license: BSD 3-Clause
